### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by RUSshy** [ngbrown/nhibernate-core#1]
Hello, 

I have tried #NH-3807 but it refuse to build

I also tried the 2nd most recent branch #NH-4008

It build but get the following error for a MySQL db

```bat

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.File
NotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The
system cannot find the file specified.
   at MySql.Data.MySqlClient.MySqlConnectAttrs.get_OSDetails()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MySql.Data.MySqlClient.NativeDriver.SetConnectAttrs()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.Authenticate(Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare()
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactoryImplementor sessionFactory)
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at Test.Server.Database.Repositories.NHibernateHelper.BuildSessionFactory() in C:\Users\RUSshy\dev\Test\proj\src\Test.Server
\Database\Repositories\NHibernateHelper.cs:line 34
   at Test.Server.Database.ServerDatabase.InitializeSql() in C:\Users\RUSshy\dev\Test\proj\src\Test.Server\Database\ServerDB.cs
:line 16
   at Test.Server.Program.Main(String[] args) in C:\Users\RUSshy\dev\Test\proj\src\Test.Server\Program.cs:line 34
```

**Comment by RUSshy** [comment]
any idea? i really need nhibernate for my project :(

**Comment by ngbrown** [comment]
@RUSshy Are you trying to run this under .NET Core 2.0?  If not, then use the [standard NuGet package](https://www.nuget.org/packages/NHibernate/) and [normal documentation](http://nhibernate.info/).

**Comment by ngbrown** [comment]
If this is with `dotnet` then can you paste the results of `dotnet --info`.  You may have to try different versions of the [MySql.Data driver](https://www.nuget.org/packages/MySql.Data).  I only guessed on the minimum version and haven't tried it on Windows or Linux.

**Comment by ngbrown** [comment]
No response - closing.
